apiVersion: v1
kind: Service
metadata:
  name: {{ include "v911.name" . }}-server
  labels:
    app.kubernetes.io/name: {{ include "v911.name" . }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "v911.name" . }}
    app.kubernetes.io/component: server
